
version: '3.7'


services:

  server:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - '5000:5000'
    volumes:
      - .:/app
    working_dir: /app
    volumes:
      - .:/app
    command: flask run --host 0.0.0.0 --debugger

  db:
    image: postgres
    environment:
      - POSTGRES_DB=flask_docker_sandbox
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  
  migrations:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ~/.aws:/root/.aws
    command: flask db upgrade
