"""add email confirmation

Revision ID: 1574bad3ec8a
Revises: ccec1581ec7e
Create Date: 2022-11-05 15:10:53.302528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1574bad3ec8a'
down_revision = 'ccec1581ec7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('email_verification_dt', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_verification_dt')
    op.drop_column('users', 'email_verified')
    # ### end Alembic commands ###
