"""test and user tables

Revision ID: 8d3256aa84bf
Revises:
Create Date: 2022-06-29 13:26:15.395458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d3256aa84bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_table',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('stringfield1', sa.String(), nullable=True),
        sa.Column('stringfield2', sa.String(), nullable=True),
        sa.Column('integerfield1', sa.String(), nullable=True),
        sa.Column('integerfield2', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('username', sa.String(), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('test_table')
    # ### end Alembic commands ###
